### ISSUE TITLE
Zotero update v6.0 makes plugins from v5 incompatible

### ISSUE THREAD

**Issue by welpdx** [whacked/zotero-special-tags-column#2]
Zotero update v6.0 makes current plugin incompatible. Just a heads up.

#### But it's a easy fix to get the plugin compatible with new zotero version:
https://github.com/ethanwillis/zotero-scihub/issues/67
https://github.com/eschnett/zotero-citationcounts/issues/18

#### Also check if your plugin works after updating. Scite made some ppl's database crash or something.  
https://forums.zotero.org/discussion/95418/scite-plugin-not-working-zotero-6-0-1
https://github.com/scitedotai/scite-zotero-plugin/issues/38#issue-1176159307

#### Also Idk if custom columns are working now. I don't see it working with Scite and bbt. Maybe it is just me. 
Found this interesting:
https://github.com/scitedotai/scite-zotero-plugin/pull/26

Edit: nvm, custom columns are working fine

**Comment by whacked** [comment]
I admit I haven't upgraded yet

**Comment by welpdx** [comment]
Ah gotcha, no worries. 
Yea, it's gonna be some work to get custom columns working for Zotero V6

**Comment by whacked** [comment]
I upgraded and pushed an updated plugin. It works for me, hope it does for you too!

**Comment by welpdx** [comment]
Worked for me after manually installing the xpi. 
Excellent! Thank you
